### ISSUE TITLE
pseudobulk

### ISSUE THREAD

**Issue by chrkuo** [FridleyLab/spatialGE#4]
Hi is it true that spatialGE allows users to create a pseudobulk matrix from spatial data?

**Comment by oospina** [comment]
Hi. Yes, defined as the sum of of counts across all spots/cell within a spatial sample. 
The matrix can be accessed from the STlist as `stlist@misc$scaled_pbulk_mtx`

Oscar

**Comment by chrkuo** [comment]
> Hi. Yes, defined as the sum of of counts across all spots/cell within a spatial sample. 
> 
> The matrix can be accessed from the STlist as `stlist@misc$scaled_pbulk_mtx`
> 
> 
> 
> Oscar
> 
> 

Thank you. I tried to use the web version yesterday and it seems like i can't use pseudo bulk unless there's more than 3 samples. Is that just the issue with web interface

**Comment by chrkuo** [comment]
> It's the web interface. The reason is pseudobulk count calculation is followed by PCA. Also, please note that currently the pseudobulk matrix cannot be downloaded from the web interface.
> 
> Oscar 

Thank you! 

So theoretically i could use this to generate spatial pseudo bulk and perform downstream analysis with CIBERSORTx etc?

**Comment by chrkuo** [comment]
@oospina 

I just tried it on R to do STlist but came an error:

> ews4521 <- STlist(rnacounts=visium_folders)
Error in STlist(rnacounts = visium_folders) : 
  Input not recognized. Please refer to documentation.
  
  I specified the visium_folders which contain the h5 file and the spatial subfolder any thoughts?

**Comment by oospina** [comment]
> So theoretically i could use this to generate spatial pseudo bulk and perform downstream analysis with CIBERSORTx etc?

You could, but as far I understand it, it might not be advisable. The pseudocounts generated by `pseudobulk_samples` are not length-normalized (if I remember well, CIBERSORT prefers something like TPM counts). But without knowing what the goal is, this comment might not be correct.

**Comment by oospina** [comment]
> @oospina
> 
> I just tried it on R to do STlist but came an error:
> 
> > ews4521 <- STlist(rnacounts=visium_folders)
> > Error in STlist(rnacounts = visium_folders) :
> > Input not recognized. Please refer to documentation.
> 
> I specified the visium_folders which contain the h5 file and the spatial subfolder any thoughts?

Assuming `visium_folders` is a vector with file paths following the Space Ranger output (h5 + spatial folder with tissue_positions_list.csv), then what’s missing in the command is the `samples` argument. That argument should contain a vector of sample names that matches the names of the visium folders.

**Comment by oospina** [comment]
Closing, but please feel free to re-open if there are issues.
